/**
 * Copies contract ABIs from the Foundry build output (evm/out) into typed
 * TypeScript modules under lib/evm/abi/. Run after changing contracts:
 *
 *   (cd evm && forge build) && node scripts/sync-evm-abi.cjs
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "evm", "out");
const abiDir = path.join(root, "lib", "evm", "abi");

const targets = [
  {
    artifact: path.join(outDir, "CoopLaunchpad.sol", "CoopLaunchpad.json"),
    file: "coopLaunchpad.ts",
    exportName: "coopLaunchpadAbi",
  },
  {
    artifact: path.join(outDir, "CoopLaunchToken.sol", "CoopLaunchToken.json"),
    file: "coopLaunchToken.ts",
    exportName: "coopLaunchTokenAbi",
  },
  {
    artifact: path.join(outDir, "CoopLocker.sol", "CoopLocker.json"),
    file: "coopLocker.ts",
    exportName: "coopLockerAbi",
  },
  {
    artifact: path.join(outDir, "CoopLaunchpadV2.sol", "CoopLaunchpadV2.json"),
    file: "coopLaunchpadV2.ts",
    exportName: "coopLaunchpadV2Abi",
  },
  {
    artifact: path.join(outDir, "CoopLaunchTokenV2.sol", "CoopLaunchTokenV2.json"),
    file: "coopLaunchTokenV2.ts",
    exportName: "coopLaunchTokenV2Abi",
  },
  {
    artifact: path.join(outDir, "CoopLockerV2.sol", "CoopLockerV2.json"),
    file: "coopLockerV2.ts",
    exportName: "coopLockerV2Abi",
  },
  {
    artifact: path.join(outDir, "CoopRouter.sol", "CoopRouter.json"),
    file: "coopRouter.ts",
    exportName: "coopRouterAbi",
  },
];

fs.mkdirSync(abiDir, { recursive: true });

for (const t of targets) {
  const artifact = JSON.parse(fs.readFileSync(t.artifact, "utf8"));
  const body = `// Generated by scripts/sync-evm-abi.cjs — do not edit by hand.
export const ${t.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(path.join(abiDir, t.file), body);
  console.log(`wrote lib/evm/abi/${t.file} (${artifact.abi.length} entries)`);
}

// Creation bytecode of the launch tokens — the vanity salt miner needs them to
// compute CREATE2 addresses server-side.
for (const t of [
  { sol: "CoopLaunchToken.sol", json: "CoopLaunchToken.json", file: "coopLaunchTokenBytecode.ts", exportName: "coopLaunchTokenBytecode" },
  { sol: "CoopLaunchTokenV2.sol", json: "CoopLaunchTokenV2.json", file: "coopLaunchTokenV2Bytecode.ts", exportName: "coopLaunchTokenV2Bytecode" },
]) {
  const artifact = JSON.parse(fs.readFileSync(path.join(outDir, t.sol, t.json), "utf8"));
  const body = `// Generated by scripts/sync-evm-abi.cjs — do not edit by hand.
export const ${t.exportName} = ${JSON.stringify(artifact.bytecode.object)} as \`0x\${string}\`;
`;
  fs.writeFileSync(path.join(abiDir, t.file), body);
  console.log(`wrote lib/evm/abi/${t.file}`);
}
